name: TWRP Recovery Builder (Tutorial Local Edition)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout Device Tree
      uses: actions/checkout@v4
      with:
        path: device/ulefone/Armor_15

    - name: Setup Build Environment
      run: |
        sudo apt-get update || true
        sudo apt-get install -y bc bison build-essential ccache curl flex g++-multilib gcc-multilib git gnupg gperf lib32readline-dev lib32z1-dev liblz4-tool libncurses5-dev libssl-dev libxml2 libxml2-utils lzop pngcrush rsync schedtool squashfs-tools xsltproc zip zlib1g-dev xz-utils || true

    - name: Download Artifact From Release
      uses: robinraju/release-downloader@v1.11
      with:
        # Hier sind jetzt deine echten Repository-Daten eingetragen:
        repository: "Libotor/twrp_device_Ulefone_Armor15"
        tag: "v1.0.0"
        fileName: "MinimalOmniRecovery-twrp-6.0-norepo-20200222.tar.xz"

    - name: Extract Local Precompiled TWRP Source
      run: |
        mkdir -p twrp_source
        tar -xJf MinimalOmniRecovery-twrp-6.0-norepo-20200222.tar.xz --directory twrp_source/
        rm MinimalOmniRecovery-twrp-6.0-norepo-20200222.tar.xz
        
        # Verschiebe deinen hochgeladenen Device-Tree an die richtige Stelle im Quellcode
        mv device twrp_source/

    - name: Build TWRP Image
      run: |
        cd twrp_source
        source build/envsetup.sh
        lunch omni_Armor_15-eng
        make -j$(nproc) bootimage

    - name: Upload Finished Artifact
      uses: actions/upload-artifact@v4
      with:
        name: TWRP-Boot-Image-Armor15
        path: twrp_source/out/target/product/Armor_15/boot.img
